server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format-sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    username: you gmail address
    password: you gmail app password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    port: 587


